version: '3.9'

services:
  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - vector-db
    env_file:
      - .env

volumes:
  qdrant_data:
